import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import Nav from "../../components/Chat/Shared/Nav";

const playfair = Playfair_Display({
  subsets: ['latin'],
  weight: ['400', '700'], // Add weights as needed
  variable: '--font-playfair',
  display: 'swap',
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={playfair.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen overflow-hidden">
          
          <Nav />  
          <div className="flex-1 main-content transition-all lg:ml-[250px] duration-300" >
            <div  className="min-h-[100vh] lg:px-52 bg-[radial-gradient(circle_at_center,_#0a1f44_0%,_#000814_100%)] border-1 border-blue-950">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
